### ISSUE TITLE
Edge highlighting errors

### ISSUE THREAD

**Issue by matan1905** [Xstoudi/adonis-intellij#12]
Hey, I'm getting the following error:
```
com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$InvalidStateException: io.stouder.adonis.edge.file.EdgeTemplateHighlighter(io.stouder.adonis.edge.parsing.EdgeRawLexer): Error updating  after DocumentEventImpl[myOffset=1267, myOldLength=0, myNewLength=40].
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:341)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter.documentChanged(LayeredLexerEditorHighlighter.java:175)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$1(DocumentImpl.java:913)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:910)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:814)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:654)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:591)
	at com.github.copilot.editor.CopilotEditorManagerImpl.lambda$applyCompletion$3(CopilotEditorManagerImpl.java:228)
	at com.github.copilot.editor.CopilotEditorManagerImpl.wrapWithTemporarySaveVetoHandler(CopilotEditorManagerImpl.java:797)
	at com.github.copilot.editor.CopilotEditorManagerImpl.lambda$applyCompletion$4(CopilotEditorManagerImpl.java:224)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:360)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:147)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:156)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:123)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:360)
	at com.github.copilot.editor.CopilotEditorManagerImpl.applyCompletion(CopilotEditorManagerImpl.java:215)
	at com.github.copilot.editor.CopilotEditorManagerImpl.applyCompletion(CopilotEditorManagerImpl.java:203)
	at com.github.copilot.actions.CopilotApplyInlaysAction$ApplyInlaysHandler.doExecute(CopilotApplyInlaysAction.java:147)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:63)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:93)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:96)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:77)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$myActionProcessor$1.performAction(IdeKeyEventDispatcher.kt:502)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$5$lambda$4(IdeKeyEventDispatcher.kt:865)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$5(IdeKeyEventDispatcher.kt:865)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:863)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:454)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:447)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:309)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:617)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:587)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: 1267. Should be in range: [0, 1252]
	at com.intellij.openapi.editor.ex.util.SegmentArray.offsetOutOfRange(SegmentArray.java:89)
	at com.intellij.openapi.editor.ex.util.SegmentArray.findSegmentIndex(SegmentArray.java:103)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.incrementalUpdate(LexerEditorHighlighter.java:177)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:333)
	... 70 more
```

this is my code:
```
@layout('layouts/main')
@set('title', 'Generate with Workflow')

@section('body')
  <!-- Generate with Workflow Page Content -->
<div class="min-h-screen p-8" data-controller="generate">
  <form class="max-w-7xl mx-auto">
    <!-- Page Heading and Description -->
    <h1 class="text-4xl font-extrabold text-center mb-8">{{workflow.name}}</h1>
    <p class="text-2xl text-center mb-8">{{workflow.description}}</p>





    <!-- Big Prompt Text Area -->
    <textarea class="w-full h-32 rounded-lg p-4 border border-gray-300 mb-8 outline-none ring-0" placeholder="Prompt"></textarea>
 <!-- Generate Button -->
    <div class="text-center mb-8">
      <button class="bg-red-500 text-white font-semibold py-4 px-8 rounded-full hover:bg-red-600 transition duration-300">Generate</button>
    </div>
<!-- Section for Arguments -->
    <div class="mb-8 grid grid-cols-2 gap-4">
  <h2 class="text-2xl font-semibold col-span-2">Workflow Arguments</h2>
  @each(argument in workflow.args)
    <div class="flex flex-col">
      <label class="text-lg font-semibold" for="{{argument.name}}">
        {{argument.name}}
      </label>
      @if(argument.type === 'select')
        <select class="bg-white rounded-lg p-4 border border-gray-300 mb-8 outline-none ring-0">
          @each(option in argument.options.split(','))
            <option value="{{option.trim()}}">{{option.trim()}}</option>
          @end
        </select>
      @else
        <input
          class="rounded-lg p-4 border border-gray-300 mb-8 outline-none ring-0"
          type="{{argument.type}}"
          placeholder="{{argument.name}}"
        />
      @end
    </div>
  @end
</div>




  </form>
</div>

@end
```

Also unrelated, the icons are hella big:
<img width="239" alt="image" src="https://github.com/Xstoudi/adonis-intellij/assets/24731932/04cf51a9-a8c0-4203-ae44-eab764e19275">

**Comment by Xstoudi** [comment]
What Jetbrains IDE in what version?
What version of the Adonis plugin?

**Comment by matan1905** [comment]
IDE: WebStorm 2023.2.2 | Build #WS-232.9921.42, built on September 12, 2023
Adonis: 0.1.0

Still persists after updating IDE to 2023.2.4 | Build #WS-232.10203.14, built on October 25, 2023

Here is an image that might make it clearer
<img width="671" alt="image" src="https://github.com/Xstoudi/adonis-intellij/assets/24731932/827a5538-d180-4e4c-b58c-89072858ee27">

**Comment by Xstoudi** [comment]
Thanks a lot!
Seems the lexer is not liking the parenthesis inside the @each tag. I'll publish asap.

**Comment by Xstoudi** [comment]
Will be released in the next patch. You'll be able to download it on Github release section tonight in a few hours or on the Jetbrains Marketplace under 2 days.
